src/cleaner/queries.ts, src/handlers/models.ts, src/handlers/receptor/playbookRunCompleted.ts, src/handlers/receptor/playbookRunFinished.ts, src/handlers/receptor/queries.ts, src/handlers/receptor/receptor.integration.ts, src/handlers/receptor/sharedQueries.ts, test/migrations/20210119154303_define_additional_completed_error_fields.js, test/playbookRuns.ts
DETAILS:  Defined run-completed message migration.  Additionally I added Logic for updating these new fields with the correct responses
JIRA: https://issues.redhat.com/browse/RHCLOUD-9775
=> RHCLOUD-9775 Define run-completed migration

build/Dockerfile
Signed-off-by: Stephen Adams <tsadams@gmail.com>
=> [build] update to use node14 image

build/Dockerfile
This reverts commit 49027ea32c185d3bcd530a46a756399f9e6b1b09.
=> Revert "[build] update to use node14 image"

build/Dockerfile
Update nodejs-10 to nodejs-12    
=> Update nodejs-10 to nodejs-12

src/handlers/advisor/index.ts
=> Trigger remediations-consumer job

deployment/remediations-cleaner.yaml, deployment/remediations-consumer.yaml, deployment/remediations-update-consumer.yaml
Signed-off-by: Stephen Adams <tsadams@gmail.com>
=> [migration] move saas templates to this repo

src/db/index.ts, src/handlers/advisor/advisor.integration.ts, src/handlers/advisor/index.ts, src/handlers/compliance/compliance.integration.ts, src/handlers/compliance/index.ts, src/handlers/patch/index.ts, src/handlers/patch/patch.integration.ts, src/handlers/vulnerability/index.ts, src/handlers/vulnerability/vulnerability.integration.ts, src/probes.ts, test/producer.js
Draft PR for Streamlining update queries.
=> RHCLOUD-13989: Streamline update queries

build_deploy.sh, deployment/remediations-consumer-clowdapp.yaml, deployment/remediations-update-consumer-clowdapp.yaml, package-lock.json, package.json, pr_check.sh, src/config/index.ts, unit_test.sh
As a part of Clowderizing Remediations, shift the remediations-consumer over to Clowder support.    
=> RHCLOUD-10212: Clowderize Remediations-consumer

deployment/remediations-consumer-clowdapp.yaml, deployment/remediations-update-consumer-clowdapp.yaml
=> Update num of Replicas for update-consumer and consumer

deployment/remediations-consumer-clowdapp.yaml, deployment/remediations-update-consumer-clowdapp.yaml
=> Update Num Replicas var in both clowdapps again

deployment/remediations-consumer-clowdapp.yaml, deployment/remediations-update-consumer-clowdapp.yaml
=> Add remediations as a dependency

deployment/remediations-consumer-clowdapp.yaml, deployment/remediations-update-consumer-clowdapp.yaml
=> Remove RDS_CA var from clowdapp

src/config/index.ts
=> Update db config settings

src/config/index.ts, src/kafka/index.ts
=> Update config for clowder

src/config/index.ts
=> update kafka port to string

src/config/index.ts
=> print clowdapp config

src/config/index.ts
=> Update console statment

src/config/index.ts
=> Add CW group to clowder config later

src/config/index.ts
=> Update declaration of cloudwatch config for ephemeral

deployment/remediations-consumer-clowdapp.yaml, deployment/remediations-update-consumer-clowdapp.yaml
=> Update Cloudwatch logging to be disabled for ephemeral envs

deployment/remediations-consumer-clowdapp.yaml, deployment/remediations-update-consumer-clowdapp.yaml
=> Update metrics port

deployment/remediations-consumer-clowdapp.yaml, deployment/remediations-update-consumer-clowdapp.yaml
=> Update kafkahost and port

src/probes.ts
=> Decrease message verbosity for updated issues

deployment/remediations-consumer.yaml, deployment/remediations-update-consumer.yaml
=> QUICKFIX: Add kafka port to config file

package-lock.json, package.json
=> RHCLOUD-14770: Upgrade ws version

src/config/index.ts
=> Update clowdwatch settings

src/config/index.ts
=> QUICKFIX: Remove trouble section from clowder config

src/config/index.ts
=> Fix db ssl enabled for clowder

deployment/remediations-consumer-clowdapp.yaml, deployment/remediations-update-consumer-clowdapp.yaml, src/config/index.ts
=> QUICKFIX: update ssl-ca declaration

deployment/remediations-consumer-clowdapp.yaml, deployment/remediations-update-consumer-clowdapp.yaml, src/config/index.ts
Make use of convicts .set() function to fix an issue with clowder.    
=> Make use of convicts .set() function to fix an issue with clowder

src/config/index.ts
=> Update db.ssl.ca declaration for clowder once more

build/Dockerfile
=> Update Dockerfile with nodejs:12 and minimal image

deployment/remediations-cleaner.yaml
=> Fix the prometheus push gateway in CI and QA

deployment/remediations-consumer-clowdapp.yaml, src/cleaner/config.ts
=> Add Remediations-cleaner deployment to clowder

deployment/remediations-consumer-clowdapp.yaml
=> [QUICKFIX]: Update cleaner suspend variable

src/config/index.ts, src/kafka/index.ts
=> Update ca declaration for consumers

src/kafka/index.ts
=> Update ssl options again

deployment/remediations-consumer-clowdapp.yaml
=> Update Cleaner Suspend Field

src/config/index.ts
Add default value assignments in case ssl config does not exist.
=> Add default value to ssl config assignments

src/config/index.ts
=> Update Sasl defs once more

src/config/index.ts
Update sasl config declaration to only declare sasl stuff if it exists.    
=> Update sasl config declaration

deployment/remediations-consumer-clowdapp.yaml, deployment/remediations-update-consumer-clowdapp.yaml, package.json, src/config/index.ts, test/seeds/initial.js, unit_test.sh
=> Kafka ca debug

src/config/index.ts, src/kafka/index.ts, unit_test.sh
=> Update kafka config for managed kafka

src/config/index.ts
Remove sasl.securityProtocol field    
=> Remove sasl.securityProtocol

src/kafka/index.ts
=> Make sasl config correct

src/config/index.ts, src/kafka/index.ts
=> Fix kafka topics

src/kafka/index.ts
=> Increase kafak connection timeout to 10 seconds

package-lock.json, package.json, src/cleaner/config.ts
=> Added convict_format_with_validator package for url support

deployment/remediations-consumer-clowdapp.yaml, src/config/index.ts, src/kafka/index.ts
=> Made new config parameter for kafka connection timeout value

package-lock.json, package.json
=> Added convict-format-with-validator package

build/Dockerfile, build/docker-compose-unit_test.yml, build/docker-compose.yml, package.json, pr_check.sh, src/config/index.ts, tsconfig.json, unit_test.sh
=> REMEDY-245 Containerize pr_check

.gitignore, build/Dockerfile, build/docker-compose-unit_test.yml, jest.config.js, package-lock.json, package.json, pr_check.sh, src/cleaner/config.ts, src/cleaner/probes.ts, src/config/formats.unit.ts, src/config/index.ts, src/kafka/index.ts, src/util/log.ts, test/playbookRuns.ts, tsconfig.json, unit_test.sh
=> Remedy-245 upgrade to  node.js v16

build/docker-compose.yml, package-lock.json, package.json
=> Add missing tmp package

build/Dockerfile, build/docker-compose.yml
=> FIX: Add package.json to dist image

src/util/log.ts
=> FIX: pino-cloudwatch import

build/Dockerfile, build/docker-compose-unit_test.yml, jest.config.js, package.json, src/cleaner/config.ts, unit_test.sh
=> REMEDY-259: Set specific ubi-minimal version

build/Dockerfile
=> REMEDY-276: Updated parent image

build/Dockerfile
=> Removed unnescessary yum install

CODEOWNERS, build/Dockerfile
=> Upgrade to ubi-minimal:8.7-1049

build/docker-compose.yml, deployment/remediations-consumer-clowdapp.yaml, src/config/index.ts, src/kafka/index.ts
=> Fix kafka tls config

build/docker-compose.yml, deployment/remediations-consumer-clowdapp.yaml, src/config/index.ts, src/kafka/index.ts
Reverts RedHatInsights/remediations-consumer#169
=> Revert "Fix kafka tls config"

src/kafka/index.ts
Make the kafka-ssl initial declaration more robust for all (and future) environments.    
=> Make kafka-ssl more robust for all envs

src/kafka/index.ts
=> Add temp debug to reveal kafka ca path

src/kafka/index.ts
Stuff kafka ssl into array for other environment usecases.
=> stuff ssl cacert into array

src/kafka/index.ts
=> Revert Kafka SSL change

src/kafka/index.ts
Reverts RedHatInsights/remediations-consumer#180
=> Revert "Back to trying putting the kafka cert in an array..."

src/kafka/index.ts
=> More comprehensive kafka config re-write

src/cleaner/config.ts, src/cleaner/probes.ts
Create METRICS_PUSH_ENABLED Enviroment Variable
=> Create PUSH_METRICS_ENABLED env var

deployment/remediations-cleaner.yaml
Update deploy file with new param
=> Update deploy file with new param

deployment/remediations-consumer-clowdapp.yaml, deployment/remediations-update-consumer-clowdapp.yaml, src/config/index.ts, src/kafka/index.ts
Added key to ssl creds and added subsiquent env vars for both options changed.
- Add key to ssl creds
- Add additional env vars
=> Add Key to ssl creds

src/config/index.ts, src/kafka/index.ts
=> Fix kafka client config to handle basic case used in production

src/kafka/index.ts
=> More kafka config shenanigans

src/kafka/index.ts
=> Debugging kafka client config in prod

src/config/index.ts
=> Log cdappconfig STRUCTURE (not contents) to console.log for debug

src/config/index.ts, src/kafka/index.ts
=> Print generated kafka config keys to console for debug

src/config/index.ts, src/kafka/index.ts
=> Still more kafka client config changes

deployment/remediations-consumer-clowdapp.yaml, src/config/index.ts
=> Remove extraneous env vars from clowdapp

deployment/remediations-consumer-clowdapp.yaml, deployment/remediations-update-consumer-clowdapp.yaml, src/config/index.ts, src/kafka/index.ts
=> Removed extraneous env var code

src/config/index.ts, src/kafka/index.ts
=> Fixed in valid convict definition for kafka.ssl.ca

src/config/index.ts
=> Dang it - I left out the ca part of kafka.ssl.ca :[

build/docker-compose-unit_test.yml, build/docker-compose.yml, src/config/index.ts
=> REMEDY-329: Upgrade docker-compose files to use postgres v14

build/Dockerfile, tsconfig.json
=> REMEDY-328: Enable support for sourcemaps to get better stack traces.

.github/dependabot.yml
=> REMEDY331: Configure dependabot to check for docker parent image updates.

build/Dockerfile
=> Updated url for parent docker image

.github/dependabot.yml
=> Enable npm packging checking for dependabot

.github/dependabot.yml
=> Configure dependabot to open PR's against package_updates branch

build/Dockerfile, build_deploy.sh
Update ubi8 to latest image and add Tag for security compliance tag.    
=> Update UBI-8 minimal to latest image and add tag for security-compliance

build_deploy.sh
=> Remove duplicate image tagging

build/Dockerfile
Bump ubi parent image version to address RHINENG-8104
=> Bump ubi image

src/config/index.ts
Dangit - I missed a variable initialization...
=> RHINENG-5012: Fix silly unitialized var issue

build/Dockerfile, package-lock.json, package.json
Miscellaneous package updates to address issues identified by prodsec vulnerability scan.
=> Package updates for risk mitigation

.gitignore, build/Dockerfile, build/docker-compose-unit_test.yml, build/docker-compose.yml, knexfile.js
Updated image creation process to guard against credential leakage.
=> RHINENG-9800: Update image creation process

build/Dockerfile
=> RHINENG-11286: Bump npm from 10.7.0 to 10.8.1

package.json, unit_test.sh
New build process for remediations-consumer that does not rely on podman-compose.
=> Removing podman-compose dependency from builds

build/Dockerfile
=> RHINENG-12601: Migrate from ubi8-minimal to ubi9-minimal

LICENSE, package.json
RHINENG-13423: Added a license file.
=> Add license file

deployment/remediations-consumer-clowdapp.yaml, deployment/remediations-update-consumer-clowdapp.yaml
=> Consume quay image from the konflux repo

package-lock.json, package.json
Added a version override for the async package to mitigate a security vulnerability.
=> RHINENG-11289: Added override for Async package

.cleanmodules, build/Dockerfile, package-lock.json, package.json
Adding npm clean-modules package to build to remove extraneous files from built image.
=> RHINENG-13680: add clean-modules to build process

build/docker-compose-unit_test.yml, build/docker-compose.yml, unit_test.sh
=> RHINENG-13721: Update db image to postgresql-rds:16

build/Dockerfile
=> RHINENG-13908: Rollback to ubi8-minimal

.tekton/remediations-consumer-pull-request.yaml, .tekton/remediations-consumer-push.yaml
=> RHINENG-14069: add new mandatory RPM signature scan task to tekton

.tekton/remediations-consumer-pull-request.yaml, .tekton/remediations-consumer-push.yaml
We need to pull in the latest changes for microdnf to not fail.
Note: Yes, I did it all very securely!
=> build: Update buildah task

build/Dockerfile
=> RHINENG-14308: Upgrade rpm packages

package-lock.json, package.json
=> RHINENG-14281: Upgrade cross-spawn to 7.0.6

package-lock.json
=> Bump braces from 3.0.2 to 3.0.3

package-lock.json
=> RHINENG-16035: Bump cross-spawn to 7.0.6

.tekton/remediations-consumer-pull-request.yaml, .tekton/remediations-consumer-push.yaml
=> Update tekton pipelines - add tasks - SAST Unicode and Shell Check tasks/SAST Coverity Check tasks

deployment/remediations-update-consumer-clowdapp.yaml
=> RHINENG-18476: Update Clowder kafkaTopics
